apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a-deployment  # Deployment Name
  namespace : kubernetes-practice-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
      - name: microservice-a
        image: araina97/microservicea
        imagePullPolicy: IfNotPresent                 
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
           name : microservice-a-config-cm

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a-service  # Service Name
  namespace : kubernetes-practice-namespace
spec:
  selector:
    app: microservice-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
